### PR TITLE
Updated footer.html

### PR DESCRIPTION
**Pull request by SachinHatikankar100**
added dev social svg icon

### CODE REVIEW

**Comment by SachinHatikankar100** [comment]
Hi @pedropintosilva requesting more assistance. I am seeing a screen with these below lines. What should be the next step? 

```
pick 1b7939f Update faq.md
pick 32d3957 Replace Hacktoberfest with testfest

# Rebase cef5016..32d3957 onto cef5016 (2 commands)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup <commit> = like "squash", but discard this commit's log message
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
# .       create a merge commit using the original merge commit's
# .       message (or the oneline, if no original merge commit was
# .       specified). Use -c <commit> to reword the commit message.
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
```

**Comment by pedropintosilva** [comment]
> pick 1b7939f Update faq.md
> pick 32d3957 Replace Hacktoberfest with testfest

This ^ doesn't look right. Are you sure you are in the right branch?

**Comment by pedropintosilva** [comment]
if I checkout your `patch-5` branch this what I see (`git log --pretty=oneline`):
```bash
dfa2629688c9694adcabf4f9bfe51d4680a6e6d2 (HEAD -> patch-5) Updated footer.html
7535a0be550c8d4602bdf32e86014587b0db577c Updated footer.html
dee70070fddd8dc9a0101f61c4652616600a5582 Add Moodle integration slides
[...]
```

**Comment by pedropintosilva** [comment]
do you see the same?

**Comment by SachinHatikankar100** [comment]
Hi @pedropintosilva thanks for your inputs. I will check out and work accordingly or will reach out incase of queries

**Comment by SachinHatikankar100** [comment]
Hi @pedropintosilva Thanks for the guidance. Requesting review

**Comment by pedropintosilva** [comment]
Thanks @SachinHatikankar100 !

**Pull request merged**
